import React from 'react'

export default function Footer() {
    return (
        <div className="footer-wraper" >
            <div className="col main">
                <img className="logo-loship" src="/assets/images/logo.png" alt="logo-loship" />
                <p>Công ty Cổ Phần Lozi Việt Nam</p>
                <p />
                <p><b>Tòa nhà Lữ Gia, Tầng 4 - 70 Lữ Gia - F.15 - Q11 - Tp. Hồ Chí Minh</b></p>
                <p>Tổng đài giải đáp thắc mắc về Loship: <a className="support-loship" href="mailto:hotroloship@lozi.vn" title="hotroloship@lozi.vn">hotroloship@lozi.vn</a></p>
                <p><a href="tel:1900638058" title="Hotline: " style={{ color: 'rgb(92, 92, 92)' }}>Hotline: <b>1900.638.058</b></a></p>
                <p>Liên hệ hợp tác / tài trợ: <a className="support-loship" href="mailto:uyennhu@lozi.vn" title="uyennhu@lozi.vn">uyennhu@lozi.vn</a></p>
                <p>Liên hệ truyền thông: <a className="support-loship" href="mailto:press@loship.vn" title="press@loship.vn">press@loship.vn</a></p>
                <p><a to="https://loship.vn/quy-che?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Quy chế hoạt động trên Loship.vn" href="https://loship.vn/quy-che?utm_source=https://loship.vn&utm_medium=footer">Quy chế hoạt động trên Loship.vn</a></p>
                <p className="special-info mt-16">Giấy CNĐKDN: 0313546809 – Ngày cấp: 24/11/2015, được sửa đổi lần thứ 1 ngày 01/04/2016.</p>
                <p className="special-info">Cơ quan cấp: Phòng Đăng ký kinh doanh – Sở kế hoạch và Đầu tư TP.HCM</p>
                <p className="special-info">Địa chỉ đăng ký kinh doanh: Lầu 4, Tòa nhà Mirae, 268 Tô Hiến Thành, Phường 15, Quận 10, Tp. Hồ Chí Minh, Việt Nam.</p>
                <a href="http://online.gov.vn/Home/WebDetails/43990" title="BCT"><img src="" alt="Logo BCT" height="40px" /></a>
            </div>
            <div className="col">
                <h3>Dịch Vụ</h3>
                <a className="col-item" href="https://loship.vn/about?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="LOSHIP - giao đồ ăn" rel="noreferrer">LOSHIP - giao đồ ăn</a><a className="col-item" href="https://lomart.vn/gioi-thieu?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="LOMART - đi chợ" rel="noreferrer">LOMART - đi chợ</a><a className="col-item" href="https://zat.loship.vn/gioi-thieu?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="LOZAT - giặt ủi" rel="noreferrer">LOZAT - giặt ủi</a><a className="col-item" href="https://loship.vn/lopoint?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="LOPOINT - tích điểm" rel="noreferrer">LOPOINT - tích điểm</a><a className="col-item" href="https://med.loship.vn/gioi-thieu?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="LOMED - giao thuốc" rel="noreferrer">LOMED - giao thuốc</a><a className="col-item" href="https://loship.vn/quy-che/losend?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="LO-SEND - vận chuyển" rel="noreferrer">LO-SEND - vận chuyển</a><a className="col-item" href="https://loship.vn/gioi-thieu/lo-hoa?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="LOHOA - giao hoa" rel="noreferrer">LOHOA - giao hoa</a><a className="col-item" href="https://loship.vn/gioi-thieu/lo-pet?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="LOPET - giao vật dụng thú cưng" rel="noreferrer">LOPET - giao vật dụng thú cưng</a><a className="col-item" href="https://losupply.vn?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="LOSUPPLY - giao nguyên vật liệu cho chủ cửa hảng" rel="noreferrer">LOSUPPLY - giao nguyên vật liệu cho chủ cửa hảng</a><a className="col-item" href="https://loship.vn/UngDungCuaHang?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Ứng dụng Loship - Chủ cửa hàng" rel="noreferrer">Ứng dụng Loship - Chủ cửa hàng</a>
            </div>
            <div className="col">
                <h3>Hợp tác</h3>
                <a className="col-item" href="https://doitacloship.lozi.vn?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Mở cửa hàng trên LOSHIP" rel="noreferrer">Mở cửa hàng trên LOSHIP</a><a className="col-item" href="https://dangkylomart.lozi.vn?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Mở cửa hàng trên LOMART" rel="noreferrer">Mở cửa hàng trên LOMART</a><a className="col-item" href="https://doitaclozat.lozi.vn?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Mở cửa hàng trên LOZAT" rel="noreferrer">Mở cửa hàng trên LOZAT</a><a className="col-item" href="https://doitaclomed.lozi.vn?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Mở cửa hàng trên LOMED" rel="noreferrer">Mở cửa hàng trên LOMED</a><a className="col-item" href="https://doitaclohoa.lozi.vn?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Mở cửa hàng trên LOHOA" rel="noreferrer">Mở cửa hàng trên LOHOA</a><a className="col-item" href="https://doitaclopet.lozi.vn?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Mở cửa hàng trên LOPET" rel="noreferrer">Mở cửa hàng trên LOPET</a><a className="col-item" href="https://hoptacvoiloship.lozi.vn?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Hợp tác về Marketing" rel="noreferrer">Hợp tác về Marketing</a><a className="col-item" href="https://loship.vn/careers?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Tuyển dụng" rel="noreferrer">Tuyển dụng</a>
                <h3>Tài xế Loship</h3>
                <a className="col-item" href="http://chienbinhloship.com?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Trở thành chiến binh LOSHIP" rel="noreferrer">Trở thành chiến binh LOSHIP</a><a className="col-item" href="https://loship.vn/tuyen-dung/quy-tac-ung-xu?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Quy tắc ứng xử của Chiến binh Loship" rel="noreferrer">Quy tắc ứng xử của Chiến binh Loship</a><a className="col-item" href="https://loship.vn/tuyen-dung/cau-hoi-thuong-gap?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Câu hỏi thường gặp" rel="noreferrer">Câu hỏi thường gặp</a><a className="col-item" href="https://loship.vn/tuyen-dung/tram-dung-loship?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Trạm dừng Loship" rel="noreferrer">Trạm dừng Loship</a><a className="col-item" href="https://loship.vn/tuyen-dung/bi-kip-di-don?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Bí kíp đi đơn" rel="noreferrer">Bí kíp đi đơn</a>
            </div>
            <div className="col">
                <h3>Loship khu vực</h3>
                <a className="col-item" href="/ho-chi-minh?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship - Hồ Chí Minh" rel="noreferrer">Loship - Hồ Chí Minh</a><a className="col-item" href="/ha-noi?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship - Hà Nội" rel="noreferrer">Loship - Hà Nội</a><a className="col-item" href="/da-nang?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship - Đà Nẵng" rel="noreferrer">Loship - Đà Nẵng</a><a className="col-item" href="/can-tho?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship - Cần Thơ" rel="noreferrer">Loship - Cần Thơ</a><a className="col-item" href="/dong-nai?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship - Đồng Nai" rel="noreferrer">Loship - Đồng Nai</a><a className="col-item" href="/hai-phong?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship - Hải Phòng" rel="noreferrer">Loship - Hải Phòng</a><a className="col-item" href="/quang-ninh?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship - Quảng Ninh" rel="noreferrer">Loship - Quảng Ninh</a><a className="col-item" href="/thua-thien-hue?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship - Thừa Thiên Huế" rel="noreferrer">Loship - Thừa Thiên Huế</a><a className="col-item" href="/khanh-hoa?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship - Khánh Hòa" rel="noreferrer">Loship - Khánh Hòa</a><a className="col-item" href="/ba-ria-vung-tau?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship - Bà Rịa - Vũng Tàu" rel="noreferrer">Loship - Bà Rịa - Vũng Tàu</a><a className="col-item" href="/quang-nam?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship - Quảng Nam" rel="noreferrer">Loship - Quảng Nam</a>
            </div>
            <div className="col">
                <h3>Media</h3>
                <a className="col-item" href="http://bit.ly/gioi-thieu-ve-loship?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Giới thiệu đúng về Loship" rel="noreferrer">Giới thiệu đúng về Loship</a><a className="col-item" href="http://bit.ly/allaboutlogoloship?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Tải logo Loship cho Media" rel="noreferrer">Tải logo Loship cho Media</a><a className="col-item" href="http://loship.vn/welcome?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="Loship introduction" rel="noreferrer">Loship introduction</a>
                <h3>Tải Ứng Dụng</h3>
                <a className="col-item icon-app apple" href="http://bit.ly/Loship_iOS?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="App iOS" rel="noreferrer">App iOS</a><a className="col-item icon-app android" href="http://bit.ly/LOSHIPonAndroid?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="App Android" rel="noreferrer">App Android</a><a className="col-item icon-app huawei" href="https://appgallery.huawei.com/#/app/C102529537?utm_source=https://loship.vn&utm_medium=footer" target="_blank" title="App Huawei" rel="noreferrer">App Huawei</a>
                <hr />
                <h3>Kết nối với chúng tôi</h3>
                <p className="item-social"><a to="https://www.facebook.com/LoshipVN/" className="social link-fb" target="_blank" href="https://www.facebook.com/LoshipVN/" /><a to="https://wmww.instagram.com/loshipvn/" className="social link-ins" target="_blank" href="https://wmww.instagram.com/loshipvn/" /></p>
                <div className="language-switcher dropdown-wrapper footer-language-menu">
                    <div className="selected"><a><img src="" className="icon" alt="vi_VN" />Vietnamese</a><i className="lz lz-triangle-down" /></div>
                    <div className="dropdown-menu centered">
                        <ul>
                            <li className="dropdown-item"><a className="has-icon change-language" data-change="vi_VN"><img src="" className="icon" alt="vi_VN" /><span>Vietnamese</span></a></li>
                            <li className="dropdown-item"><a className="has-icon change-language" data-change="en_US"><img src="" className="icon" alt="en_US" /><span>English</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    )
}
